import React from 'react';
import { TabsContent } from '@/components/ui/tabs';
import KPICards from './KPICards';
import ProductivityChart from './ProductivityChart';
import StatusChart from './StatusChart';
import TeamMetrics from './TeamMetrics';
import ActivityFeed from './ActivityFeed';
import MigrationPhasesSection from './MigrationPhasesSection';
import TenantManagement from './TenantManagement';
import AIToolsSection from './AIToolsSection';
import ReportsSection from './ReportsSection';
import AutoGeneratedReports from './AutoGeneratedReports';
import RealTimeEnvironmentPanel from './RealTimeEnvironmentPanel';
import QuickSetupCard from './QuickSetupCard';

interface DashboardContentProps {
  dashboardData: any;
  companyLogo: string | null;
  o365Settings: any;
  onSettingsChange: (settings: any) => void;
}

const DashboardContent = ({ dashboardData, companyLogo, o365Settings, onSettingsChange }: DashboardContentProps) => {
  return (
    <>
      {/* Overview Tab */}
      <TabsContent value="overview" className="space-y-6">
        <RealTimeEnvironmentPanel />
        <KPICards metrics={dashboardData.teamMetrics} />
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <ProductivityChart data={dashboardData.productivityData} />
          <StatusChart data={dashboardData.statusData} />
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <TeamMetrics productivityData={dashboardData.productivityData} />
          <ActivityFeed />
        </div>
      </TabsContent>

      {/* Analytics Tab */}
      <TabsContent value="analytics" className="space-y-6">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <ProductivityChart data={dashboardData.productivityData} />
          <StatusChart data={dashboardData.statusData} />
        </div>
        <TeamMetrics productivityData={dashboardData.productivityData} />
      </TabsContent>

      {/* Migration Tab */}
      <TabsContent value="migration" className="space-y-6">
        <QuickSetupCard onSettingsChange={onSettingsChange} />
        <MigrationPhasesSection />
      </TabsContent>


      {/* Tenants Tab */}
      <TabsContent value="tenants" className="space-y-6">
        <TenantManagement />
      </TabsContent>



      {/* Auto Reports Tab */}
      <TabsContent value="auto-reports" className="space-y-6">
        <AutoGeneratedReports />
      </TabsContent>

      {/* AI Tools Tab */}
      <TabsContent value="ai-tools" className="space-y-6">
        <AIToolsSection />
      </TabsContent>

      {/* Reports Tab */}
      <TabsContent value="reports" className="space-y-6">
        <ReportsSection 
          dashboardData={dashboardData}
          companyLogo={companyLogo}
          o365Settings={o365Settings}
        />
      </TabsContent>
    </>
  );
};

export default DashboardContent;